name: qaza_tracker
description: Tracking and calculating missed prayers
publish_to: 'none'
version: 2.2.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.2
  easy_localization: ^3.0.1
  shared_preferences: ^2.1.0
  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  equatable: ^2.0.5
  keyboard_dismisser: ^3.0.0
  formz: ^0.6.0
  json_annotation: ^4.8.1
  meta: ^1.8.0
  flutter_svg: ^2.0.5
  google_sign_in: ^6.1.0
  firebase_crashlytics: ^3.1.1
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.1
  syncfusion_flutter_datepicker: ^21.1.41
  cached_network_image: ^3.2.3
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/translations/