// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb3J5Bsbj0x5Uov1OQuzilO9x3NduVBKA',
    appId: '1:612068716776:web:30f03e26ca10f2eb67995d',
    messagingSenderId: '612068716776',
    projectId: 'qaza-tracker-01',
    authDomain: 'qaza-tracker-01.firebaseapp.com',
    storageBucket: 'qaza-tracker-01.appspot.com',
    measurementId: 'G-261DGX0BH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKPrX-G7GAkOl7pdhDxyXdU7Uclo1VV2Q',
    appId: '1:612068716776:android:ebef6c103944b5d567995d',
    messagingSenderId: '612068716776',
    projectId: 'qaza-tracker-01',
    storageBucket: 'qaza-tracker-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4xLygb58kBA4ZyeKp7NbJ5Y_4AiBFu7s',
    appId: '1:612068716776:ios:e2f2e8876bc0929267995d',
    messagingSenderId: '612068716776',
    projectId: 'qaza-tracker-01',
    storageBucket: 'qaza-tracker-01.appspot.com',
    androidClientId:
        '612068716776-9rp4b6t786ig96stdcgn5i5l63h90mbs.apps.googleusercontent.com',
    iosClientId:
        '612068716776-jd5vto0is849d0r6mh57qn67qum3b9tu.apps.googleusercontent.com',
    iosBundleId: 'uz.bahrom.qazaTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4xLygb58kBA4ZyeKp7NbJ5Y_4AiBFu7s',
    appId: '1:612068716776:ios:e2f2e8876bc0929267995d',
    messagingSenderId: '612068716776',
    projectId: 'qaza-tracker-01',
    storageBucket: 'qaza-tracker-01.appspot.com',
    androidClientId:
        '612068716776-9rp4b6t786ig96stdcgn5i5l63h90mbs.apps.googleusercontent.com',
    iosClientId:
        '612068716776-jd5vto0is849d0r6mh57qn67qum3b9tu.apps.googleusercontent.com',
    iosBundleId: 'uz.bahrom.qazaTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb3J5Bsbj0x5Uov1OQuzilO9x3NduVBKA',
    appId: '1:612068716776:web:db62da1f25e3857967995d',
    messagingSenderId: '612068716776',
    projectId: 'qaza-tracker-01',
    authDomain: 'qaza-tracker-01.firebaseapp.com',
    storageBucket: 'qaza-tracker-01.appspot.com',
    measurementId: 'G-1H11VQQNEB',
  );
}
